import { defineStore } from 'pinia'
import AvatarImage from '@/assets/images/avatar.png'
import VerificationPhotoImage from '@/assets/images/verification-photo.png'
import PhotoImage from '@/assets/images/photo.png'

export const useModerationStore = defineStore('moderation', {
  state: () => ({
    list: [
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },

      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
      {
        avatar: AvatarImage,
        verificationPhoto: VerificationPhotoImage,
        userId: '632121',
        country: 'Россия',
        city: 'Москва',
        age: 18,
        about:
          'Человек выского ума, занимаюсь бизнесом по продаже машин, ищу спутницу жизни',
        photos: [
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
          PhotoImage,
        ],
      },
    ],
  }),
})
